#!/bin/bash

# Paths
BASE_PATH="/etc/gitpaas"
SOURCE_PATH="$BASE_PATH/source"
MAIN_TRAEFIK_PATH="$BASE_PATH/traefik"
DYNAMIC_TRAEFIK_PATH="$MAIN_TRAEFIK_PATH/dynamic"
LOGS_PATH="$BASE_PATH/logs"
APPLICATIONS_PATH="$BASE_PATH/applications"
SSH_PATH="$BASE_PATH/ssh"
CERTIFICATES_PATH="$DYNAMIC_TRAEFIK_PATH/certificates"
MONITORING_PATH="$BASE_PATH/monitoring"
SCHEDULES_PATH="$BASE_PATH/schedules"
VOLUME_BACKUPS_PATH="$BASE_PATH/volume-backups"