#!/bin/bash

# Traefik ports and version
TRAEFIK_SSL_PORT="${TRAEFIK_SSL_PORT:-443}"
TRAEFIK_PORT="${TRAEFIK_PORT:-80}"
TRAEFIK_HTTP3_PORT="${TRAEFIK_HTTP3_PORT:-443}"
TRAEFIK_VERSION="${TRAEFIK_VERSION:-3.6.10}"